@protocol = https
@host = localhost
@port = 8421
@base_url = {{protocol}}://{{host}}:{{port}}

GET {{base_url}}

###

POST {{base_url}}/auth-code
Content-Type: application/json

{
  "sms": "123456",
  "secret": "super_secret"
}
